---
# handlers file for consul
- name: Restart consul
  command: /sbin/restart consul
  sudo: yes
  notify:
    - wait for consul to listen

- name: wait for consul to listen
  wait_for:
    host: "{{ consul_bind_addr }}"
    port: 8500
